services:
  core:
    image: hetao29/docker-php-fpm-nginx:latest
    ports:
        - "10000:80"
    networks:
        - network
    volumes:
        - www:/var/www/html
    deploy:
      replicas: 2 
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 2
        delay: 10s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
networks:
    network:
        name: com_mxiqi_network
        external: true
volumes:
  www:
    driver: local
